### ISSUE TITLE
Create new auth handling logic 

### ISSUE THREAD

**Issue by pvj** [lahmacunradio/arcsi#126]
As mentioned in #107 we are in the middle of creating auth handling views that lets us decouple from the current dependency that handles our auth routes & views. 

In order to remove that dep we have to adopt some auth logic that authenticates & authorises incoming requests.

For that we must change our api route handling: 
 - All requests are only valid if an active, existing token is passed -- preferably in the header
 - All invalid requests should be returned w/ 403 Forbidden HTTP status
 - Tokens should be generated by combination of current date + server-side secret + unique user data -- this should be handled by our newly selected auth provider plugin
 - Token generation and refresh, destruction etc. should be tied to user actions (login, logout etc.)
 - Tokens should be stored along w/ users

**Comment by tuz666** [comment]
Resolved in [the following PR](https://github.com/lahmacunradio/arcsi/pull/156)
